server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lw476781393/springcloud-demo.git #配置git仓库地址
          searchPaths: configs #配置仓库路径
          username: lw476781393 #访问git仓库的用户名
          password: leiwen1988 #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/