server:
  port: 8084

spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh