eureka:
  client:
    serviceUrl:
#     spring.application.name 为该服务的名字，eureka.client.serviceUrl.defaultZone 的作用是指定注册中心的地址。
      defaultZone: http://127.0.0.1:8081/eureka/
server:
  port: 8082
spring:
  application:
    name: eurekaclient